### ISSUE TITLE
Working for 2D? 

### ISSUE THREAD

**Issue by sxdxs** [vaughanb/UnityMultiplayerARPG_LootBag#1]
I have tried but does not seem to work! It looks a little different in 2D. I tried a few different places in CanvasGameplay but they seem to throw me the 'Saving failed' error everytime.

**Comment by vaughanb** [comment]
Unfortunately this does not yet work for 2D. I will add it for a future release.

**Comment by vaughanb** [comment]
UPDATE: There isn't enough demand for the 2D version for me to justify spending the time on it. I do not expect to fix this.
